name: Integración Continua Proyecto Aleyumy

on:
  push:
    branches:
      - principal

  pull_request:
    branches:
      - principal

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permisos a Maven Wrapper
      run: chmod +x aleyumy/mvnw

    - name: Compilar proyecto Spring Boot
      run: cd aleyumy && ./mvnw clean
    install
